### ISSUE TITLE
Flashing the new hex gives errors 

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/BetterDuinoFirmwareV4#4]
I tried flashing the new latest hex using the same settings as the ver before hand but now get a error and no commands display in the monitor window using command #MD00 or #MD01 like on last ver the window stays blank.

![image](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/e7df0c95-d2db-452b-870c-5d1005577e80)

**Comment by RealNobser** [comment]
Yes, the hex file was corrupt, I have to renew.

**Comment by stewartgill1977** [comment]
Great Thanks

**Comment by RealNobser** [comment]
I replaced the firmware by the correct hex file. I accidently uploaded the elf file instead of the hex file.
