### ISSUE TITLE
6 servo imputs for lower dome.

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/BetterDuinoFirmwareV4#6]
6 servo inputs for lower dome but new dome v4 has 7 servos is there a extra input for it. I know there is one for the magic panel but not sure where the 7 lower panel one is. 
![image](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/5f0508ec-8c9f-4a9d-906a-170b387d1f68)

![image](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/0e74ad9d-57ba-476f-9cc8-d65214002569)

**Comment by RealNobser** [comment]
Mr. Baddeley added two additional panels, the small ones right and left beside the logic light. So there a 8 lower panels and 4 pie panels now. These are not supported by default BetterDuino or MarcDuino boards or animations. Of course you can use Servo 11 on Master board and Servo 12 and 13 on Slave board (aka 10 and 11) to control them nevertheless. But then you are on your own for adapting the animations etc. for now.

**Comment by stewartgill1977** [comment]
Hi no there are 7 one extra hmmm ill take a look at the code and see if i can work it out. Im not much of a programmer but can do a little thanks
![image](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/ad8f087b-1319-491c-a583-41c0a84bc9af)

**Comment by stewartgill1977** [comment]
I think i get it i just edit this eg the servos like 12 or 13 to opn  and cls the servo input i use. The only thing i see being a pain is if i update the firmware will it copy over what i changed?.
![image](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/fc016aac-973b-46c8-9195-9236c96a41e5)

**Comment by RealNobser** [comment]
Overwrite might happen. So the best way would be, you create a fork for yourself and only sync changes from my side to your repository if needed.
