### ISSUE TITLE
Holo lights 

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/BetterDuinoFirmwareV4#7]
Hi just finished wiring everything up and none of the holos light up on start up or commands. I tested them before i put them in on the desk and the worked. I have a funny felling it may of been the older ver of the firmware but i can not remember. I have checked voltage and i'm getting 5v to the lights. I also plugged then into a servo tester and they also did not turn on i'm not shore if they need a signal or something and that's why they do not turn on with the servo tester ??.I did also try using the bench power supply at 5v and power them direct still no go all 3 with is weird as they where fine before hand. Sorry don't know much about them but this is what i'm using. https://electropeak.com/7-bit-ws2812-round-led-light-module WS2812 7-Bit RGB LED Ring Module. Also the holo servos do not move when commanded i hear them power up on command and move slightly then stop but no automation eg full awake mode. Tested servos and they are good

**Comment by RealNobser** [comment]
Which version of Betterduino? Have you configured the NeoPixels correctly (correct number of LEDs)? Did you use the NeoPixel firmware or the standard firmware? NeoPixels need some memory, so you will find a master+slave-only firmware with NeoPixel support separately in each version.
Here is the recent officially supported version: https://github.com/RealNobser/BetterDuinoFirmwareV4/releases/tag/v1.0.11

**Comment by stewartgill1977** [comment]
yep thats the ver im running the latest.  "Have you configured the NeoPixels correctly" I just plugged them in was working before but not shore what firmware i was using may of been the older but im on the newest one now have not entered any commands do i need to to get them to work with the latest ver?

**Comment by stewartgill1977** [comment]
ooo do i need the bottom ver??? that could be why i have loaded the top ver?
![Untitled](https://github.com/RealNobser/BetterDuinoFirmwareV4/assets/37970956/5ffa9f19-1ac1-4e01-86ca-582f0b8a5202)

**Comment by RealNobser** [comment]
Yes...
